"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { Camera, Menu, X } from "lucide-react";
const links = [["Work","/work"],["About","/about"],["Services","/services"],["Journal","/journal"],["Contact","/contact"]];
export function Mark(){return <span className="brand-mark"><b>B</b><b>28</b></span>}
export function SiteHeader(){const [open,setOpen]=useState(false); const pathname=usePathname(); useEffect(()=>setOpen(false),[pathname]); return <header className="site-header"><Link href="/" className="brand" aria-label="B28 Entertainment home"><Mark/><span>B28<br/>Entertainment</span></Link><nav aria-label="Primary navigation">{links.map(([label,href])=><Link className={pathname===href?"active":""} key={href} href={href}>{label}</Link>)}<Link className="nav-cta" href="/contact">Start a project</Link></nav><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu"><span>Menu</span>{open?<X/>:<Menu/>}</button><div id="mobile-menu" className={`mobile-menu ${open?"open":""}`} aria-hidden={!open}><div className="mobile-menu-inner"><p className="eyebrow">B28 / Navigate</p>{links.map(([label,href],i)=><Link href={href} key={href}><span>0{i+1}</span>{label}</Link>)}<div className="mobile-bottom"><p>Nairobi, Kenya<br/>Available worldwide</p><Link href="/contact" className="button light">Start a project</Link></div></div></div></header>}
export function SiteFooter(){return <footer className="site-footer"><div className="wrap footer-grid"><div><Link href="/" className="brand"><Mark/><span>B28<br/>Entertainment</span></Link><p>Independent production studio<br/>Nairobi, Kenya</p></div><div><p className="footer-label">Explore</p>{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div><div><p className="footer-label">Connect</p><a href="mailto:hello@b28entertainment.com">hello@b28entertainment.com</a><a href="#" aria-label="Instagram"><Camera size={18}/> Instagram</a></div><div className="footer-big">Stories<br/><em>that stay.</em></div></div><div className="wrap legal"><span>© {new Date().getFullYear()} B28 Entertainment</span><span>Demo content is clearly marked in the CMS.</span><Link href="/admin">Admin</Link></div></footer>}
