"use client";

import { Copy, Eye, EyeOff, ImagePlus, Link2, Plus, Trash2, Type, Video } from "lucide-react";
import type { SelectedVisualElement } from "@/components/public/visual-editor-runtime";
import type { CustomElement, ElementOverride, SiteSettings } from "@/lib/site-settings";

type Props = { selected: SelectedVisualElement | null; path: string; settings: SiteSettings; onChange: (settings: SiteSettings) => void; onApply: (override: ElementOverride) => void; onUpload: (receiver: (path: string) => void) => void; onClose: () => void };

function id() { return typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }

export function ElementInspector({ selected, path, settings, onChange, onApply, onUpload, onClose }: Props) {
  const existing = selected ? settings.elementOverrides.find((item) => item.path === selected.path && item.selector === selected.selector) : undefined;
  const override: ElementOverride | null = selected ? existing || { id: id(), path: selected.path, selector: selected.selector, tag: selected.tag, styles: {} } : null;
  const update = (patch: Partial<ElementOverride>) => {
    if (!override) return;
    const next = { ...override, ...patch };
    const rest = settings.elementOverrides.filter((item) => !(item.path === next.path && item.selector === next.selector));
    onChange({ ...settings, elementOverrides: [...rest, next] }); onApply(next);
  };
  const style = (property: string, value: string) => update({ styles: { ...override?.styles, [property]: value } });
  const add = (type: CustomElement["type"]) => {
    const url = type === "embed" ? window.prompt("Paste a YouTube, Vimeo, or other embeddable URL") : null;
    if (type === "embed" && !url) return;
    const item: CustomElement = { id: id(), path, type, content: type === "heading" ? "New heading" : type === "button" ? "New button" : type === "text" ? "New text. Click it to edit." : type === "embed" ? "Embedded media" : "", src: type === "image" ? "/media/b28-logo.jpg" : url || "", href: type === "button" ? "/contact" : "", order: settings.customElements.filter((entry) => entry.path === path).length, anchorSelector: selected?.selector || ".site-shell main > :first-child", placement: "after", styles: type === "heading" ? { "font-size": "48px" } : type === "image" || type === "embed" ? { width: "100%" } : {} };
    onChange({ ...settings, customElements: [...settings.customElements, item] });
  };
  const addBackground = () => {
    if (!selected) return;
    onUpload((value) => update({ styles: { ...override?.styles, "background-image": `url("${value}")`, "background-size": "cover", "background-position": "center" } }));
  };
  const duplicate = () => {
    if (!selected) return;
    const type: CustomElement["type"] = selected.tag === "img" ? "image" : selected.tag === "iframe" ? "embed" : /^h[1-6]$/.test(selected.tag) ? "heading" : selected.tag === "a" || selected.tag === "button" ? "button" : "text";
    const item: CustomElement = { id: id(), path, type, content: selected.text, src: selected.src, href: selected.href, order: settings.customElements.filter((entry) => entry.path === path).length, anchorSelector: selected.selector, placement: "after", styles: { ...override?.styles } };
    onChange({ ...settings, customElements: [...settings.customElements, item] });
  };
  const remove = () => {
    if (!selected) return;
    const customMatch = selected.selector.match(/custom-([^"\]]+)/);
    if (customMatch) { onChange({ ...settings, customElements: settings.customElements.filter((item) => item.id !== customMatch[1]) }); onClose(); }
    else update({ hidden: true });
  };
  return <div className="builder-element-editor">
    <div className="builder-section-title"><div><small>Click-to-edit canvas</small><strong>{selected ? selected.label || selected.tag : "Select an element"}</strong></div>{selected && <button onClick={onClose}>×</button>}</div>
    {!selected ? <div className="builder-element-empty"><p>Click any text, image, button, section, card, menu item, or footer element directly in the canvas. New elements are placed after that selection.</p><strong>Add near the first section</strong><div className="builder-add-elements"><button onClick={() => add("heading")}><Type size={14}/> Heading</button><button onClick={() => add("text")}><Plus size={14}/> Text</button><button onClick={() => add("image")}><ImagePlus size={14}/> Image block</button><button onClick={() => add("embed")}><Video size={14}/> Video / embed</button><button onClick={() => add("button")}><Link2 size={14}/> Button / link</button><button onClick={() => add("divider")}><Plus size={14}/> Divider</button><button onClick={() => add("spacer")}><Plus size={14}/> Spacer</button></div></div> : <div className="builder-fields">
      <p className="builder-field-note">Editing one <strong>{selected.tag}</strong> on <strong>{selected.path}</strong>. Changes appear immediately and publish with the site design.</p>
      {selected.canEditText && <label>Text<textarea value={override?.text ?? selected.text} onChange={(event) => update({ text: event.target.value })}/></label>}
      {selected.tag === "img" && <><label>Image<div className="builder-media-field"><input value={override?.src ?? selected.src} onChange={(event) => update({ src: event.target.value })}/><button onClick={() => onUpload((value) => update({ src: value }))}><ImagePlus size={14}/></button></div></label><label>Image description<input value={override?.alt ?? selected.alt} onChange={(event) => update({ alt: event.target.value })}/></label></>}
      {selected.tag === "a" && <label>Link URL<input value={override?.href ?? selected.href} onChange={(event) => update({ href: event.target.value })}/></label>}
      <div className="builder-field-group"><strong>Typography & color</strong><label>Text color<input value={override?.styles.color ?? selected.styles.color} onChange={(event) => style("color", event.target.value)}/></label><label>Background color<input value={override?.styles["background-color"] ?? selected.styles["background-color"]} onChange={(event) => style("background-color", event.target.value)}/></label><label>Background image<div className="builder-media-field"><input value={override?.styles["background-image"] || ""} onChange={(event) => style("background-image", event.target.value)} placeholder={'url("/media/image.jpg")'}/><button onClick={() => onUpload((value) => style("background-image", `url("${value}")`))}><ImagePlus size={14}/></button></div></label><label>Background sizing<select value={override?.styles["background-size"] || "cover"} onChange={(event) => style("background-size", event.target.value)}><option value="cover">Cover</option><option value="contain">Contain</option><option value="auto">Original</option></select></label><label>Font family<input value={override?.styles["font-family"] ?? selected.styles["font-family"]} onChange={(event) => style("font-family", event.target.value)}/></label><label>Font size<input value={override?.styles["font-size"] ?? selected.styles["font-size"]} onChange={(event) => style("font-size", event.target.value)} placeholder="48px"/></label><label>Font weight<input value={override?.styles["font-weight"] ?? selected.styles["font-weight"]} onChange={(event) => style("font-weight", event.target.value)}/></label><label>Alignment<select value={override?.styles["text-align"] ?? selected.styles["text-align"]} onChange={(event) => style("text-align", event.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option><option value="justify">Justify</option></select></label><label>Line height<input value={override?.styles["line-height"] ?? selected.styles["line-height"]} onChange={(event) => style("line-height", event.target.value)}/></label><label>Letter spacing<input value={override?.styles["letter-spacing"] ?? selected.styles["letter-spacing"]} onChange={(event) => style("letter-spacing", event.target.value)}/></label></div>
      <div className="builder-field-group"><strong>Size & spacing</strong><label>Width<input value={override?.styles.width ?? selected.styles.width} onChange={(event) => style("width", event.target.value)}/></label><label>Height<input value={override?.styles.height ?? selected.styles.height} onChange={(event) => style("height", event.target.value)}/></label><label>Padding<input value={override?.styles.padding ?? selected.styles.padding} onChange={(event) => style("padding", event.target.value)}/></label><label>Margin<input value={override?.styles.margin ?? selected.styles.margin} onChange={(event) => style("margin", event.target.value)}/></label><label>Corner radius<input value={override?.styles["border-radius"] ?? selected.styles["border-radius"]} onChange={(event) => style("border-radius", event.target.value)}/></label><label>Border<input value={override?.styles.border || ""} onChange={(event) => style("border", event.target.value)} placeholder="1px solid #ffffff"/></label><label>Shadow<input value={override?.styles["box-shadow"] || ""} onChange={(event) => style("box-shadow", event.target.value)} placeholder="0 12px 40px #00000066"/></label><label>Opacity<input value={override?.styles.opacity ?? selected.styles.opacity} onChange={(event) => style("opacity", event.target.value)}/></label>{selected.tag === "img" && <label>Image fit<select value={override?.styles["object-fit"] || "cover"} onChange={(event) => style("object-fit", event.target.value)}><option value="cover">Cover</option><option value="contain">Contain</option><option value="fill">Stretch</option><option value="none">Original</option></select></label>}</div>
      <div className="builder-field-group"><strong>Position</strong><label>Position<select value={override?.styles.position || ""} onChange={(event) => style("position", event.target.value)}><option value="">Normal flow</option><option value="relative">Relative</option><option value="absolute">Absolute</option><option value="fixed">Fixed</option><option value="sticky">Sticky</option></select></label><label>Top<input value={override?.styles.top || ""} onChange={(event) => style("top", event.target.value)} placeholder="0px"/></label><label>Left<input value={override?.styles.left || ""} onChange={(event) => style("left", event.target.value)} placeholder="0px"/></label><label>Layer / z-index<input value={override?.styles["z-index"] || ""} onChange={(event) => style("z-index", event.target.value)}/></label></div>
      <div className="builder-element-actions"><button onClick={duplicate}><Copy size={14}/> Duplicate</button><button onClick={() => update({ hidden: !override?.hidden })}>{override?.hidden ? <Eye size={14}/> : <EyeOff size={14}/>}{override?.hidden ? "Show" : "Hide"}</button><button className="danger" onClick={remove}><Trash2 size={14}/> Remove</button></div>
      <div className="builder-add-elements"><button onClick={() => add("heading")}><Type size={14}/> Add heading</button><button onClick={() => add("text")}><Plus size={14}/> Add text</button><button onClick={addBackground}><ImagePlus size={14}/> Background image</button><button onClick={() => add("image")}><ImagePlus size={14}/> Image block</button><button onClick={() => add("embed")}><Video size={14}/> Video / embed</button><button onClick={() => add("button")}><Link2 size={14}/> Button / link</button></div>
    </div>}
  </div>;
}
